//! Project scan — 프로젝트 추가 시 백그라운드에서 규칙 문서를 인덱싱하고,
//! 비어있거나 누락된 규칙 문서를 안전 규칙 하에 보강한다.
//!
//! 핵심 원칙:
//! - rich/partial 등급 문서는 절대 건드리지 않음 (AUTO-GENERATED 마커가 없으면)
//! - 출력: `{path}/.cortx/project-context.md` + 기록한 `ProjectMetadata` 이벤트
//!
//! pty.rs/shell.rs와 동일하게 `thread::spawn` + `AppHandle::emit()` 패턴 사용.
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use tauri::{AppHandle, Emitter};

const SCANNER_VERSION: u32 = 1;
const AUTO_GEN_MARKER: &str = "<!-- AUTO-GENERATED by cortx";
const CONTEXT_FILE_REL: &str = ".cortx/project-context.md";
const SCAN_IGNORE_DIRS: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "vendor",
    ".cortx",
    ".venv",
    "__pycache__",
];
const MAX_TREE_FILES: usize = 500;

// ── Types (TS `ProjectMetadata`와 대칭) ─────────────────────────

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq)]
#[serde(rename_all = "lowercase")]
enum DocGrade {
    Rich,
    Partial,
    Empty,
    Missing,
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
struct DocEntry {
    path: String,
    grade: DocGrade,
    size_bytes: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    first_h1: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Copy)]
#[serde(rename_all = "snake_case")]
enum SotStatus {
    Resolved,
    ReferencedButEmpty,
    None,
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq)]
#[serde(rename_all = "lowercase")]
enum ProjectQuality {
    Rich,
    Partial,
    Sparse,
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ProjectMetadata {
    scanned_at: String,
    scanner_version: u32,
    tech_stack: Vec<String>,
    claude_md: DocEntry,
    agents_md: DocEntry,
    ai_docs: Vec<DocEntry>,
    #[serde(skip_serializing_if = "Option::is_none")]
    sot_doc: Option<String>,
    sot_status: SotStatus,
    context_file_path: String,
    used_fallback: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    file_count: Option<u64>,
    overall_quality: ProjectQuality,
    auto_generated_files: Vec<String>,
    auto_fill_enabled: bool,
}

// ── Helpers ─────────────────────────────────────────────────────

/// 파일의 유효성 등급을 산정한다. 파일 크기·마크다운 구조·마커 존재 여부를 종합.
fn grade_document(path: &Path) -> (DocGrade, u64, Option<String>) {
    let Ok(meta) = fs::metadata(path) else {
        return (DocGrade::Missing, 0, None);
    };
    let size = meta.len();
    let Ok(content) = fs::read_to_string(path) else {
        return (DocGrade::Missing, size, None);
    };

    // AUTO-GENERATED 마커가 있으면 "재작성 가능" 상태로 empty 취급
    if content.contains(AUTO_GEN_MARKER) {
        return (DocGrade::Empty, size, extract_first_h1(&content));
    }

    // 공백/HTML 주석/해시 주석만 있는지 확인
    let stripped = strip_comments_and_whitespace(&content);
    if stripped.trim().is_empty() || stripped.len() < 20 {
        return (DocGrade::Empty, size, extract_first_h1(&content));
    }

    let h2_count = content.lines().filter(|l| l.starts_with("## ")).count();
    let has_bullet_or_table =
        content.lines().any(|l| l.trim_start().starts_with("- ") || l.trim_start().starts_with("| "));
    let first_h1 = extract_first_h1(&content);

    let grade = if size >= 500 && h2_count >= 2 && has_bullet_or_table {
        DocGrade::Rich
    } else if size >= 100 {
        DocGrade::Partial
    } else {
        DocGrade::Empty
    };
    (grade, size, first_h1)
}

fn extract_first_h1(content: &str) -> Option<String> {
    content
        .lines()
        .find(|l| l.starts_with("# "))
        .map(|l| l.trim_start_matches("# ").trim().to_string())
}

fn strip_comments_and_whitespace(content: &str) -> String {
    let mut out = String::with_capacity(content.len());
    let mut in_html_comment = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if in_html_comment {
            if trimmed.contains("-->") {
                in_html_comment = false;
            }
            continue;
        }
        if trimmed.starts_with("<!--") && !trimmed.contains("-->") {
            in_html_comment = true;
            continue;
        }
        if trimmed.starts_with("<!--") && trimmed.contains("-->") {
            continue;
        }
        out.push_str(trimmed);
        out.push('\n');
    }
    out
}

fn read_to_string_safe(path: &Path) -> Option<String> {
    fs::read_to_string(path).ok()
}

/// CLAUDE.md 류 문서에서 "## 섹션_이름" 블록을 통째로 추출.
/// 다음 `## ` 헤더 또는 파일 끝까지를 반환.
fn extract_section(content: &str, headings: &[&str]) -> Option<String> {
    let lines: Vec<&str> = content.lines().collect();
    for (i, line) in lines.iter().enumerate() {
        if !line.starts_with("## ") {
            continue;
        }
        let title = line.trim_start_matches("## ").trim().to_lowercase();
        let matched = headings.iter().any(|h| title.contains(&h.to_lowercase()));
        if !matched {
            continue;
        }
        let mut out = String::new();
        for next in &lines[i + 1..] {
            if next.starts_with("## ") {
                break;
            }
            out.push_str(next);
            out.push('\n');
        }
        let trimmed = out.trim().to_string();
        if trimmed.is_empty() {
            return None;
        }
        return Some(trimmed);
    }
    None
}

/// CLAUDE.md에서 `SOT: {경로}` 패턴을 찾아 경로 반환 (따옴표/백틱 제거).
fn extract_sot_path(content: &str) -> Option<String> {
    for line in content.lines() {
        if let Some(idx) = line.find("SOT:") {
            let rest = line[idx + "SOT:".len()..].trim();
            // 첫 번째 경로 토큰만 추출 — 백틱/따옴표 제거
            let cleaned: String = rest
                .chars()
                .take_while(|c| !c.is_whitespace() || *c == '/' || *c == '.')
                .filter(|c| *c != '`' && *c != '"' && *c != '\'' && *c != '*')
                .collect();
            let trimmed = cleaned.trim().trim_end_matches(&[',', '.', ';'][..]);
            if !trimmed.is_empty() && trimmed.contains('.') {
                return Some(trimmed.to_string());
            }
        }
    }
    None
}

// ── Manifest parsing ────────────────────────────────────────────

/// 루트 매니페스트 파일을 스캔해 감지된 기술 스택 문자열 목록 반환.
fn detect_tech_stack(root: &Path) -> Vec<String> {
    let mut stack: Vec<String> = Vec::new();

    // package.json
    if let Some(content) = read_to_string_safe(&root.join("package.json")) {
        stack.push("Node.js".to_string());
        if content.contains("\"next\"") {
            stack.push("Next.js".to_string());
        } else if content.contains("\"react\"") {
            stack.push("React".to_string());
        }
        if content.contains("\"express\"") {
            stack.push("Express".to_string());
        }
        if content.contains("\"@nestjs/core\"") {
            stack.push("NestJS".to_string());
        }
        if content.contains("\"vue\"") {
            stack.push("Vue".to_string());
        }
        if content.contains("\"@tauri-apps/api\"") {
            stack.push("Tauri".to_string());
        }
        if content.contains("\"typescript\"") {
            stack.push("TypeScript".to_string());
        }
    }

    // Cargo.toml
    if let Some(content) = read_to_string_safe(&root.join("Cargo.toml")) {
        stack.push("Rust".to_string());
        if content.contains("tauri") {
            stack.push("Tauri".to_string());
        }
        if content.contains("axum") {
            stack.push("Axum".to_string());
        }
        if content.contains("actix") {
            stack.push("Actix".to_string());
        }
    }

    // go.mod
    if read_to_string_safe(&root.join("go.mod")).is_some() {
        stack.push("Go".to_string());
    }

    // Python
    if let Some(content) = read_to_string_safe(&root.join("pyproject.toml")) {
        stack.push("Python".to_string());
        if content.contains("fastapi") {
            stack.push("FastAPI".to_string());
        }
        if content.contains("django") {
            stack.push("Django".to_string());
        }
    } else if root.join("requirements.txt").exists() {
        stack.push("Python".to_string());
    }

    // Java / JVM
    let gradle_kts = root.join("build.gradle.kts");
    let gradle = root.join("build.gradle");
    let pom = root.join("pom.xml");
    if let Some(content) = read_to_string_safe(&gradle_kts).or_else(|| read_to_string_safe(&gradle)) {
        stack.push("Java/Gradle".to_string());
        if let Some(ver) = extract_gradle_java_version(&content) {
            stack.push(format!("Java {}", ver));
        }
        if content.contains("spring-boot") {
            stack.push("Spring Boot".to_string());
        }
        if content.contains("queryDsl") || content.contains("querydsl") {
            stack.push("QueryDSL".to_string());
        }
    } else if let Some(content) = read_to_string_safe(&pom) {
        stack.push("Java/Maven".to_string());
        if content.contains("spring-boot") {
            stack.push("Spring Boot".to_string());
        }
    }

    // 중복 제거 (순서 유지)
    let mut seen: Vec<String> = Vec::new();
    for item in stack {
        if !seen.contains(&item) {
            seen.push(item);
        }
    }
    seen
}

fn extract_gradle_java_version(content: &str) -> Option<String> {
    for line in content.lines() {
        let l = line.trim();
        if let Some(rest) = l.strip_prefix("sourceCompatibility") {
            return Some(rest.trim_start_matches(['=', ' ']).trim().trim_matches('"').to_string());
        }
        if l.starts_with("jvmTarget") {
            return Some(
                l.trim_start_matches("jvmTarget")
                    .trim_start_matches(['=', ' '])
                    .trim()
                    .trim_matches('"')
                    .to_string(),
            );
        }
    }
    None
}

// ── File tree fallback ─────────────────────────────────────────

/// depth 제한 하에 상위 디렉토리/파일 목록을 수집 (fallback).
fn collect_file_tree(root: &Path, max_depth: usize) -> (Vec<String>, u64) {
    let mut entries: Vec<String> = Vec::new();
    let mut total_count: u64 = 0;
    walk_tree(root, root, 0, max_depth, &mut entries, &mut total_count);
    entries.sort();
    (entries, total_count)
}

fn walk_tree(
    root: &Path,
    dir: &Path,
    depth: usize,
    max_depth: usize,
    entries: &mut Vec<String>,
    count: &mut u64,
) {
    if depth > max_depth || entries.len() >= MAX_TREE_FILES {
        return;
    }
    let Ok(reader) = fs::read_dir(dir) else {
        return;
    };
    for entry in reader.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') && name != ".ai" {
            continue;
        }
        if SCAN_IGNORE_DIRS.contains(&name.as_str()) {
            continue;
        }
        let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().to_string();
        if path.is_dir() {
            entries.push(format!("{}/", rel));
            walk_tree(root, &path, depth + 1, max_depth, entries, count);
        } else {
            *count += 1;
            if depth <= max_depth && entries.len() < MAX_TREE_FILES {
                entries.push(rel);
            }
        }
    }
}

fn collect_language_histogram(root: &Path) -> Vec<(String, u64)> {
    use std::collections::HashMap;
    let mut counts: HashMap<String, u64> = HashMap::new();
    count_exts(root, root, 0, 4, &mut counts);
    let mut vec: Vec<(String, u64)> = counts.into_iter().collect();
    vec.sort_by(|a, b| b.1.cmp(&a.1));
    vec.into_iter().take(5).collect()
}

fn count_exts(root: &Path, dir: &Path, depth: usize, max_depth: usize, counts: &mut std::collections::HashMap<String, u64>) {
    if depth > max_depth {
        return;
    }
    let Ok(reader) = fs::read_dir(dir) else { return };
    for entry in reader.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') && name != ".ai" {
            continue;
        }
        if SCAN_IGNORE_DIRS.contains(&name.as_str()) {
            continue;
        }
        if path.is_dir() {
            count_exts(root, &path, depth + 1, max_depth, counts);
        } else if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
            *counts.entry(ext.to_lowercase()).or_insert(0) += 1;
        }
    }
}

// ── Context file composition ───────────────────────────────────

#[allow(clippy::too_many_arguments)]
fn compose_context_md(
    project_name: &str,
    scanned_at: &str,
    tech_stack: &[String],
    claude_md: &DocEntry,
    agents_md: &DocEntry,
    ai_docs: &[DocEntry],
    sot_doc: &Option<String>,
    sot_status: SotStatus,
    quality: ProjectQuality,
    used_fallback: bool,
    claude_content: &Option<String>,
    tree_entries: &[String],
    lang_hist: &[(String, u64)],
    readme_excerpt: &Option<String>,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Project Context — {}\n", project_name));
    out.push_str(&format!(
        "_Generated: {} | Scanner: cortx v{}_\n\n",
        scanned_at, SCANNER_VERSION
    ));

    // Scan Quality 배너
    out.push_str("## Scan Quality\n");
    out.push_str(&format!("- Overall: **{}**\n", quality_label(quality)));
    match sot_status {
        SotStatus::Resolved => {
            if let Some(p) = sot_doc {
                out.push_str(&format!("- SOT: `{}`\n", p));
            }
        }
        SotStatus::ReferencedButEmpty => {
            out.push_str(&format!(
                "- ⚠️ SOT `{}`가 참조되었으나 비어있음 — dev-task가 질문해야 할 항목\n",
                sot_doc.clone().unwrap_or_else(|| "?".into())
            ));
        }
        SotStatus::None => {
            out.push_str("- SOT: 지정되지 않음\n");
        }
    }
    if used_fallback {
        out.push_str("- ⚠️ 규칙 문서 부족 — fallback (파일 트리/언어 통계)로 보완\n");
    }
    out.push('\n');

    // Tech Stack
    out.push_str("## Tech Stack\n");
    if tech_stack.is_empty() {
        out.push_str("_감지된 매니페스트 없음_\n");
    } else {
        for t in tech_stack {
            out.push_str(&format!("- {}\n", t));
        }
    }
    out.push('\n');

    // Rule Files
    out.push_str("## Rule Files\n");
    out.push_str(&format!(
        "- `CLAUDE.md`: **{}** ({} bytes)\n",
        grade_label(claude_md.grade),
        claude_md.size_bytes
    ));
    out.push_str(&format!(
        "- `AGENTS.md`: **{}** ({} bytes)\n",
        grade_label(agents_md.grade),
        agents_md.size_bytes
    ));
    if !ai_docs.is_empty() {
        out.push_str("- `.ai/docs/`:\n");
        for d in ai_docs {
            out.push_str(&format!(
                "  - `{}` — {} ({} bytes)\n",
                d.path,
                grade_label(d.grade),
                d.size_bytes
            ));
        }
    }
    out.push('\n');

    // CLAUDE.md 추출 섹션 (grade >= partial 일 때만)
    if let Some(content) = claude_content {
        if let Some(table) = extract_section(
            content,
            &["작업 유형", "task-type", "task type", "트리거", "trigger"],
        ) {
            out.push_str("## Task-Type → Doc Mapping (from CLAUDE.md)\n");
            out.push_str(&table);
            out.push_str("\n\n");
        }
        if let Some(rules) = extract_section(content, &["즉시 규칙", "immediate rules"]) {
            out.push_str("## Immediate Rules (verbatim)\n");
            out.push_str(&rules);
            out.push_str("\n\n");
        }
        if let Some(pitfalls) = extract_section(
            content,
            &["반복 지적", "반복 지적 패턴", "common pitfalls", "금지 패턴"],
        ) {
            out.push_str("## Common Pitfalls (verbatim)\n");
            out.push_str(&pitfalls);
            out.push_str("\n\n");
        }
        if let Some(forbidden) = extract_section(content, &["금지 경로", "forbidden"]) {
            out.push_str("## Forbidden Paths\n");
            out.push_str(&forbidden);
            out.push_str("\n\n");
        }
    }

    // Fallback sections
    if used_fallback {
        if let Some(readme) = readme_excerpt {
            out.push_str("## README (excerpt)\n```\n");
            out.push_str(readme);
            out.push_str("\n```\n\n");
        }
        if !lang_hist.is_empty() {
            out.push_str("## Language Histogram (top 5 by file count)\n");
            for (ext, count) in lang_hist {
                out.push_str(&format!("- `.{}`: {}\n", ext, count));
            }
            out.push('\n');
        }
        if !tree_entries.is_empty() {
            out.push_str("## File Tree (depth 2)\n```\n");
            for e in tree_entries.iter().take(100) {
                out.push_str(e);
                out.push('\n');
            }
            out.push_str("```\n");
        }
    }

    out
}

fn grade_label(g: DocGrade) -> &'static str {
    match g {
        DocGrade::Rich => "rich",
        DocGrade::Partial => "partial",
        DocGrade::Empty => "empty",
        DocGrade::Missing => "missing",
    }
}

fn quality_label(q: ProjectQuality) -> &'static str {
    match q {
        ProjectQuality::Rich => "rich",
        ProjectQuality::Partial => "partial",
        ProjectQuality::Sparse => "sparse",
    }
}

// ── Auto-fill scaffolds ────────────────────────────────────────

fn auto_gen_header(now: &str) -> String {
    format!(
        "{} v{} on {} — edit freely, remove marker when curated -->\n\n",
        AUTO_GEN_MARKER, SCANNER_VERSION, now
    )
}

fn scaffold_claude_md(project_name: &str, now: &str, tech_stack: &[String], modules: &[String]) -> String {
    let mut s = auto_gen_header(now);
    s.push_str(&format!("# {} — 개발 규칙\n\n", project_name));
    s.push_str("## 즉시 규칙\n\n");
    s.push_str("- 커밋/PR 전 코드 컨벤션 확인\n");
    s.push_str("- 테스트 없이 상태 변경 로직 머지 금지\n");
    s.push_str("- `main`/`master` 직접 푸시 금지, 피처 브랜치 사용\n\n");

    if !tech_stack.is_empty() {
        s.push_str("## 기술 스택\n\n");
        for t in tech_stack {
            s.push_str(&format!("- {}\n", t));
        }
        s.push('\n');
    }

    if !modules.is_empty() {
        s.push_str("## 모듈\n\n");
        for m in modules {
            s.push_str(&format!("- `{}`\n", m));
        }
        s.push('\n');
    }

    s.push_str("## 작업 유형별 로드 규칙\n\n");
    s.push_str("| 트리거 | 로드 대상 | 비고 |\n");
    s.push_str("|---|---|---|\n");
    s.push_str("| 구현/리팩토링 | `.ai/docs/architecture.md` | SOT 문서 |\n");
    s.push_str("| 테스트 | `.ai/docs/test_guide.md` | 테스트 규칙 |\n");
    s.push_str("| 위에 해당 없음 | 없음 | CLAUDE.md만으로 답변 |\n\n");
    s.push_str("> SOT: `.ai/docs/architecture.md`\n\n");

    s.push_str("## 반복 지적 패턴\n\n");
    s.push_str("<!-- TODO: PR 리뷰 기록에서 추출. `/pipeline:dev-task` 중 Claude가 보강 가능 -->\n");
    s
}

fn scaffold_architecture_md(
    project_name: &str,
    now: &str,
    tech_stack: &[String],
    modules: &[String],
) -> String {
    let mut s = auto_gen_header(now);
    s.push_str(&format!("# {} Architecture (초안)\n\n", project_name));
    s.push_str("## 모듈 (디렉토리 감지 기반)\n\n");
    if modules.is_empty() {
        s.push_str("<!-- TODO: 모듈 트리가 비어있음. 수동으로 채워주세요 -->\n\n");
    } else {
        for m in modules {
            s.push_str(&format!("- `{}`\n", m));
        }
        s.push('\n');
    }
    s.push_str("## Tech Stack (매니페스트 파싱)\n\n");
    for t in tech_stack {
        s.push_str(&format!("- {}\n", t));
    }
    s.push('\n');
    s.push_str("## 도메인 용어\n\n");
    s.push_str("<!-- TODO: 패키지 이름/엔티티에서 추출 예정 -->\n\n");
    s.push_str("## 금지 패턴\n\n");
    s.push_str("<!-- CLAUDE.md의 \"반복 지적 패턴\" 참고 -->\n");
    s
}

/// 최상위 디렉토리 중 "모듈" 후보 이름을 추출 (camelCase dir, 소스 포함 등).
fn detect_modules(root: &Path) -> Vec<String> {
    let Ok(reader) = fs::read_dir(root) else { return Vec::new() };
    let mut mods: Vec<String> = Vec::new();
    for entry in reader.flatten() {
        if !entry.path().is_dir() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        if SCAN_IGNORE_DIRS.contains(&name.as_str()) {
            continue;
        }
        if matches!(name.as_str(), "src" | "tests" | "test" | "docs" | "examples") {
            continue;
        }
        mods.push(name);
    }
    mods.sort();
    mods
}

/// 파일 쓰기 — 대상이 존재할 경우 grade가 Empty/Missing일 때만 덮어씀.
/// Auto-fill 안전 규칙의 최종 gate.
fn safe_write(path: &Path, content: &str) -> std::io::Result<bool> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    if path.exists() {
        let (grade, _, _) = grade_document(path);
        if grade != DocGrade::Empty && grade != DocGrade::Missing {
            return Ok(false); // protect user content
        }
    }
    fs::write(path, content)?;
    Ok(true)
}

// ── Core scan ───────────────────────────────────────────────────

fn collect_ai_docs(root: &Path) -> Vec<DocEntry> {
    let ai_dir = root.join(".ai/docs");
    let Ok(reader) = fs::read_dir(&ai_dir) else { return Vec::new() };
    let mut docs: Vec<DocEntry> = Vec::new();
    for entry in reader.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        let (grade, size, first_h1) = grade_document(&path);
        let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().to_string();
        docs.push(DocEntry {
            path: rel,
            grade,
            size_bytes: size,
            first_h1,
        });
    }
    docs.sort_by(|a, b| a.path.cmp(&b.path));
    docs
}

fn missing_doc_entry(rel: &str) -> DocEntry {
    DocEntry {
        path: rel.to_string(),
        grade: DocGrade::Missing,
        size_bytes: 0,
        first_h1: None,
    }
}

fn doc_entry_for(root: &Path, rel: &str) -> DocEntry {
    let p = root.join(rel);
    if !p.exists() {
        return missing_doc_entry(rel);
    }
    let (grade, size, first_h1) = grade_document(&p);
    DocEntry {
        path: rel.to_string(),
        grade,
        size_bytes: size,
        first_h1,
    }
}

fn overall_quality(claude: &DocEntry, agents: &DocEntry, ai_docs: &[DocEntry]) -> ProjectQuality {
    let has_rich = claude.grade == DocGrade::Rich
        || agents.grade == DocGrade::Rich
        || ai_docs.iter().any(|d| d.grade == DocGrade::Rich);
    let has_partial = claude.grade == DocGrade::Partial
        || agents.grade == DocGrade::Partial
        || ai_docs.iter().any(|d| d.grade == DocGrade::Partial);
    if has_rich {
        ProjectQuality::Rich
    } else if has_partial {
        ProjectQuality::Partial
    } else {
        ProjectQuality::Sparse
    }
}

fn do_scan(project_name: &str, project_path: &str, auto_fill: bool) -> Result<ProjectMetadata, String> {
    let root = PathBuf::from(project_path);
    if !root.is_dir() {
        return Err(format!("path is not a directory: {}", project_path));
    }

    let scanned_at = iso_now();

    // 1) Rule docs
    let claude_md = doc_entry_for(&root, "CLAUDE.md");
    let agents_md = doc_entry_for(&root, "AGENTS.md");
    let ai_docs = collect_ai_docs(&root);

    // 2) Parse CLAUDE.md if partial+
    let claude_content = if claude_md.grade == DocGrade::Rich || claude_md.grade == DocGrade::Partial {
        read_to_string_safe(&root.join("CLAUDE.md"))
    } else {
        None
    };
    let sot_doc_raw = claude_content.as_ref().and_then(|c| extract_sot_path(c));

    // 3) Tech stack
    let tech_stack = detect_tech_stack(&root);
    let modules = detect_modules(&root);

    // 4) Quality + SOT resolution
    let quality = overall_quality(&claude_md, &agents_md, &ai_docs);
    let used_fallback = matches!(quality, ProjectQuality::Sparse);

    let (sot_doc, sot_status) = if let Some(p) = sot_doc_raw.clone() {
        let entry = doc_entry_for(&root, &p);
        match entry.grade {
            DocGrade::Rich | DocGrade::Partial => (Some(p), SotStatus::Resolved),
            _ => (Some(p), SotStatus::ReferencedButEmpty),
        }
    } else {
        (None, SotStatus::None)
    };

    // 5) Fallback data
    let (tree_entries, total_files) = if used_fallback {
        let (entries, count) = collect_file_tree(&root, 2);
        (entries, Some(count))
    } else {
        (Vec::new(), None)
    };
    let lang_hist = if used_fallback {
        collect_language_histogram(&root)
    } else {
        Vec::new()
    };
    let readme_excerpt = read_to_string_safe(&root.join("README.md")).map(|c| {
        c.lines()
            .take(50)
            .collect::<Vec<_>>()
            .join("\n")
    });

    // 6) Auto-fill (before composing context, so new files are reflected)
    let mut auto_generated_files: Vec<String> = Vec::new();
    if auto_fill {
        let claude_path = root.join("CLAUDE.md");
        if matches!(claude_md.grade, DocGrade::Missing | DocGrade::Empty) {
            let content = scaffold_claude_md(project_name, &scanned_at, &tech_stack, &modules);
            if safe_write(&claude_path, &content).unwrap_or(false) {
                auto_generated_files.push("CLAUDE.md".to_string());
            }
        }

        // SOT 참조가 있으나 empty/missing인 경우 초안 생성
        if matches!(sot_status, SotStatus::ReferencedButEmpty) {
            if let Some(ref rel) = sot_doc {
                let sot_path = root.join(rel);
                let content = scaffold_architecture_md(project_name, &scanned_at, &tech_stack, &modules);
                if safe_write(&sot_path, &content).unwrap_or(false) {
                    auto_generated_files.push(rel.clone());
                }
            }
        }
    }

    // 7) Re-grade after auto-fill (files may have been created)
    let claude_md_final = doc_entry_for(&root, "CLAUDE.md");
    let agents_md_final = doc_entry_for(&root, "AGENTS.md");
    let ai_docs_final = collect_ai_docs(&root);
    let claude_content_final = if claude_md_final.grade != DocGrade::Missing {
        read_to_string_safe(&root.join("CLAUDE.md"))
    } else {
        None
    };
    let quality_final = overall_quality(&claude_md_final, &agents_md_final, &ai_docs_final);
    let used_fallback_final = matches!(quality_final, ProjectQuality::Sparse);

    // 8) Compose context file
    let context = compose_context_md(
        project_name,
        &scanned_at,
        &tech_stack,
        &claude_md_final,
        &agents_md_final,
        &ai_docs_final,
        &sot_doc,
        sot_status,
        quality_final,
        used_fallback_final,
        &claude_content_final,
        &tree_entries,
        &lang_hist,
        &readme_excerpt,
    );

    let context_path = root.join(CONTEXT_FILE_REL);
    if let Some(parent) = context_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("create .cortx/: {}", e))?;
    }
    fs::write(&context_path, &context).map_err(|e| format!("write context file: {}", e))?;

    Ok(ProjectMetadata {
        scanned_at,
        scanner_version: SCANNER_VERSION,
        tech_stack,
        claude_md: claude_md_final,
        agents_md: agents_md_final,
        ai_docs: ai_docs_final,
        sot_doc,
        sot_status,
        context_file_path: CONTEXT_FILE_REL.to_string(),
        used_fallback: used_fallback_final,
        file_count: total_files,
        overall_quality: quality_final,
        auto_generated_files,
        auto_fill_enabled: auto_fill,
    })
}

fn iso_now() -> String {
    // chrono 의존성 추가 없이 SystemTime 기반 간이 ISO 8601 (UTC, 초 단위)
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    // 연/월/일 계산: 간단히 unix_secs → ymd hms 변환
    let (y, mo, d, h, mi, s) = unix_to_ymdhms(secs as i64);
    format!("{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z", y, mo, d, h, mi, s)
}

/// 매우 단순한 unix→ymdhms 변환 (UTC). 외부 크레이트 없이 동작.
fn unix_to_ymdhms(ts: i64) -> (i32, u32, u32, u32, u32, u32) {
    let secs_per_day = 86400i64;
    let mut days = ts / secs_per_day;
    let mut rem = ts % secs_per_day;
    if rem < 0 {
        rem += secs_per_day;
        days -= 1;
    }
    let h = (rem / 3600) as u32;
    let mi = ((rem % 3600) / 60) as u32;
    let s = (rem % 60) as u32;

    // 1970-01-01 기준
    let mut year: i32 = 1970;
    loop {
        let leap = is_leap(year);
        let ydays = if leap { 366 } else { 365 };
        if days >= ydays {
            days -= ydays;
            year += 1;
        } else {
            break;
        }
    }
    let months = if is_leap(year) {
        [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    } else {
        [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    };
    let mut mo: u32 = 1;
    for m in months.iter() {
        if days >= *m {
            days -= *m;
            mo += 1;
        } else {
            break;
        }
    }
    let d = days as u32 + 1;
    (year, mo, d, h, mi, s)
}

fn is_leap(y: i32) -> bool {
    (y % 4 == 0 && y % 100 != 0) || y % 400 == 0
}

// ── Tauri command ──────────────────────────────────────────────

/// 프로젝트 루트를 스캔해 규칙 문서를 인덱싱하고, 부족한 부분을 템플릿으로 보강한다.
/// fire-and-forget — 실제 작업은 백그라운드 스레드에서 수행하고
/// `project-scan-done-{projectId}` 또는 `project-scan-error-{projectId}`로 결과를 emit한다.
#[tauri::command]
pub async fn scan_project(
    app: AppHandle,
    project_id: String,
    project_name: String,
    project_path: String,
    auto_fill: Option<bool>,
) -> Result<(), String> {
    let fill = auto_fill.unwrap_or(true);
    std::thread::spawn(move || {
        log::info!("[scan] start project={} path={} auto_fill={}", project_id, project_path, fill);
        match do_scan(&project_name, &project_path, fill) {
            Ok(metadata) => {
                let event = format!("project-scan-done-{}", project_id);
                if let Err(e) = app.emit(&event, &metadata) {
                    log::warn!("[scan] emit done failed: {}", e);
                }
            }
            Err(err) => {
                log::warn!("[scan] failed for {}: {}", project_id, err);
                let event = format!("project-scan-error-{}", project_id);
                let _ = app.emit(&event, err);
            }
        }
    });
    Ok(())
}

/// 자동 생성된 파일(AUTO-GENERATED 마커 포함)만 삭제한다. 사용자가 편집한 파일은 건너뜀.
#[tauri::command]
pub async fn remove_auto_generated(project_path: String, files: Vec<String>) -> Result<Vec<String>, String> {
    let root = PathBuf::from(&project_path);
    let mut removed: Vec<String> = Vec::new();
    for rel in files {
        let p = root.join(&rel);
        if !p.exists() {
            continue;
        }
        let Ok(content) = fs::read_to_string(&p) else { continue };
        if !content.contains(AUTO_GEN_MARKER) {
            log::info!("[scan] skip remove (marker gone): {}", rel);
            continue;
        }
        if fs::remove_file(&p).is_ok() {
            removed.push(rel);
        }
    }
    Ok(removed)
}
