/** 프로젝트 스캔 상태 표시 + 재스캔/롤백 액션. */
import { useState } from 'react';
import type { Project } from '../../types/project';
import { triggerProjectScan, removeAutoGenerated } from '../../hooks/useProjectScan';
import { QualityBadge } from './QualityBadge';
import { formatRelative } from './format';

export function ProjectScanPanel({ project }: { project: Project }) {
  const [rescanning, setRescanning] = useState(false);
  const [rollingBack, setRollingBack] = useState(false);
  const [rollbackMsg, setRollbackMsg] = useState('');
  const meta = project.metadata;

  const handleRescan = async () => {
    if (!project.localPath) return;
    setRescanning(true);
    await triggerProjectScan({
      projectId: project.id,
      projectName: project.name,
      projectPath: project.localPath,
    });
    // 이벤트 listener가 metadata를 갱신하므로 UI는 자동 업데이트
    setTimeout(() => setRescanning(false), 1500);
  };

  const handleRollback = async () => {
    if (!project.localPath || !meta || meta.autoGeneratedFiles.length === 0) return;
    setRollingBack(true);
    const removed = await removeAutoGenerated(project.localPath, meta.autoGeneratedFiles);
    setRollbackMsg(`${removed.length}개 파일 삭제됨`);
    setRollingBack(false);
    await handleRescan();
  };

  return (
    <div className="field">
      <span className="field-label">Project context</span>
      <span className="field-hint" style={{ marginBottom: 8 }}>
        `.cortx/project-context.md`에 규칙 문서를 인덱싱해 dev-task 부팅을 가속화합니다.
      </span>

      {!meta && (
        <div
          style={{
            padding: '10px 12px',
            background: 'var(--bg-chip)',
            borderRadius: 8,
            fontSize: 12,
            color: 'var(--fg-muted)',
            marginBottom: 8,
          }}
        >
          아직 스캔되지 않았습니다.
        </div>
      )}

      {meta && (
        <div
          style={{
            padding: '10px 12px',
            background: 'var(--bg-chip)',
            borderRadius: 8,
            fontSize: 12,
            marginBottom: 8,
            border: '1px solid var(--border-subtle)',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
            <QualityBadge quality={meta.overallQuality} />
            <span style={{ color: 'var(--fg-faint)', fontSize: 11 }}>scanned {formatRelative(meta.scannedAt)}</span>
          </div>
          {meta.techStack.length > 0 && (
            <div style={{ color: 'var(--fg-muted)', marginBottom: 4 }}>
              <span style={{ color: 'var(--fg-faint)' }}>Stack: </span>
              {meta.techStack.join(', ')}
            </div>
          )}
          {meta.sotStatus === 'referenced_but_empty' && meta.sotDoc && (
            <div style={{ color: '#fbbf24', marginTop: 4 }}>
              ⚠️ SOT <code>{meta.sotDoc}</code>가 비어있음
            </div>
          )}
          {meta.autoGeneratedFiles.length > 0 && (
            <div style={{ color: 'var(--fg-faint)', marginTop: 4, fontSize: 11 }}>
              자동 생성: {meta.autoGeneratedFiles.join(', ')}
            </div>
          )}
        </div>
      )}

      <div style={{ display: 'flex', gap: 8 }}>
        <button
          type="button"
          onClick={handleRescan}
          disabled={!project.localPath || rescanning}
          style={{
            padding: '6px 14px',
            background: 'var(--bg-chip)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 8,
            color: 'var(--fg-muted)',
            fontSize: 12,
            cursor: project.localPath ? 'pointer' : 'default',
            fontFamily: 'inherit',
          }}
        >
          {rescanning ? 'Scanning...' : 'Re-scan'}
        </button>
        {meta && meta.autoGeneratedFiles.length > 0 && (
          <button
            type="button"
            onClick={handleRollback}
            disabled={rollingBack}
            style={{
              padding: '6px 14px',
              background: 'transparent',
              border: '1px solid var(--border-subtle)',
              borderRadius: 8,
              color: 'var(--fg-subtle)',
              fontSize: 12,
              cursor: 'pointer',
              fontFamily: 'inherit',
            }}
          >
            {rollingBack ? 'Removing...' : '자동 생성 파일 제거'}
          </button>
        )}
      </div>
      {rollbackMsg && <div style={{ fontSize: 11, color: 'var(--fg-subtle)', marginTop: 6 }}>{rollbackMsg}</div>}
    </div>
  );
}
