//! Project scan — 프로젝트 추가 시 백그라운드에서 규칙 문서를 인덱싱하고,
//! 비어있거나 누락된 규칙 문서를 안전 규칙 하에 보강한다.
//!
//! 핵심 원칙:
//! - rich/partial 등급 문서는 절대 건드리지 않음 (AUTO-GENERATED 마커가 없으면)
//! - 출력: `{path}/.cortx/project-context.md` + 기록한 `ProjectMetadata` 이벤트
//!
//! pty.rs/shell.rs와 동일하게 `thread::spawn` + `AppHandle::emit()` 패턴 사용.
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;
use tauri::{AppHandle, Emitter};

mod fallback;
mod grader;
mod scaffold;
mod tech_stack;
mod time_utils;

use fallback::{collect_file_tree, collect_language_histogram};
use grader::{
    collect_ai_docs, doc_entry_for, extract_section, extract_sot_path, grade_label, overall_quality,
    quality_label, read_to_string_safe, DocEntry, DocGrade,
};
use scaffold::{detect_modules, safe_write, scaffold_architecture_md, scaffold_claude_md};
use tech_stack::detect_tech_stack;
use time_utils::iso_now;

const SCANNER_VERSION: u32 = 1;
const AUTO_GEN_MARKER: &str = "<!-- AUTO-GENERATED by cortx";
const CONTEXT_FILE_REL: &str = ".cortx/project-context.md";
const SCAN_IGNORE_DIRS: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "vendor",
    ".cortx",
    ".venv",
    "__pycache__",
];
const MAX_TREE_FILES: usize = 500;

// ── Types (TS `ProjectMetadata`와 대칭) ─────────────────────────
// DocGrade / DocEntry는 grader 모듈에서 re-use

#[derive(Serialize, Deserialize, Clone, Copy)]
#[serde(rename_all = "snake_case")]
enum SotStatus {
    Resolved,
    ReferencedButEmpty,
    None,
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq)]
#[serde(rename_all = "lowercase")]
enum ProjectQuality {
    Rich,
    Partial,
    Sparse,
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ProjectMetadata {
    scanned_at: String,
    scanner_version: u32,
    tech_stack: Vec<String>,
    claude_md: DocEntry,
    agents_md: DocEntry,
    ai_docs: Vec<DocEntry>,
    #[serde(skip_serializing_if = "Option::is_none")]
    sot_doc: Option<String>,
    sot_status: SotStatus,
    context_file_path: String,
    used_fallback: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    file_count: Option<u64>,
    overall_quality: ProjectQuality,
    auto_generated_files: Vec<String>,
    auto_fill_enabled: bool,
}

// ── Context file composition ───────────────────────────────────

#[allow(clippy::too_many_arguments)]
fn compose_context_md(
    project_name: &str,
    scanned_at: &str,
    tech_stack: &[String],
    claude_md: &DocEntry,
    agents_md: &DocEntry,
    ai_docs: &[DocEntry],
    sot_doc: &Option<String>,
    sot_status: SotStatus,
    quality: ProjectQuality,
    used_fallback: bool,
    claude_content: &Option<String>,
    tree_entries: &[String],
    lang_hist: &[(String, u64)],
    readme_excerpt: &Option<String>,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Project Context — {}\n", project_name));
    out.push_str(&format!(
        "_Generated: {} | Scanner: cortx v{}_\n\n",
        scanned_at, SCANNER_VERSION
    ));

    // Scan Quality 배너
    out.push_str("## Scan Quality\n");
    out.push_str(&format!("- Overall: **{}**\n", quality_label(quality)));
    match sot_status {
        SotStatus::Resolved => {
            if let Some(p) = sot_doc {
                out.push_str(&format!("- SOT: `{}`\n", p));
            }
        }
        SotStatus::ReferencedButEmpty => {
            out.push_str(&format!(
                "- ⚠️ SOT `{}`가 참조되었으나 비어있음 — dev-task가 질문해야 할 항목\n",
                sot_doc.clone().unwrap_or_else(|| "?".into())
            ));
        }
        SotStatus::None => {
            out.push_str("- SOT: 지정되지 않음\n");
        }
    }
    if used_fallback {
        out.push_str("- ⚠️ 규칙 문서 부족 — fallback (파일 트리/언어 통계)로 보완\n");
    }
    out.push('\n');

    // Tech Stack
    out.push_str("## Tech Stack\n");
    if tech_stack.is_empty() {
        out.push_str("_감지된 매니페스트 없음_\n");
    } else {
        for t in tech_stack {
            out.push_str(&format!("- {}\n", t));
        }
    }
    out.push('\n');

    // Rule Files
    out.push_str("## Rule Files\n");
    out.push_str(&format!(
        "- `CLAUDE.md`: **{}** ({} bytes)\n",
        grade_label(claude_md.grade),
        claude_md.size_bytes
    ));
    out.push_str(&format!(
        "- `AGENTS.md`: **{}** ({} bytes)\n",
        grade_label(agents_md.grade),
        agents_md.size_bytes
    ));
    if !ai_docs.is_empty() {
        out.push_str("- `.ai/docs/`:\n");
        for d in ai_docs {
            out.push_str(&format!(
                "  - `{}` — {} ({} bytes)\n",
                d.path,
                grade_label(d.grade),
                d.size_bytes
            ));
        }
    }
    out.push('\n');

    // CLAUDE.md 추출 섹션 (grade >= partial 일 때만)
    if let Some(content) = claude_content {
        if let Some(table) = extract_section(
            content,
            &["작업 유형", "task-type", "task type", "트리거", "trigger"],
        ) {
            out.push_str("## Task-Type → Doc Mapping (from CLAUDE.md)\n");
            out.push_str(&table);
            out.push_str("\n\n");
        }
        if let Some(rules) = extract_section(content, &["즉시 규칙", "immediate rules"]) {
            out.push_str("## Immediate Rules (verbatim)\n");
            out.push_str(&rules);
            out.push_str("\n\n");
        }
        if let Some(pitfalls) = extract_section(
            content,
            &["반복 지적", "반복 지적 패턴", "common pitfalls", "금지 패턴"],
        ) {
            out.push_str("## Common Pitfalls (verbatim)\n");
            out.push_str(&pitfalls);
            out.push_str("\n\n");
        }
        if let Some(forbidden) = extract_section(content, &["금지 경로", "forbidden"]) {
            out.push_str("## Forbidden Paths\n");
            out.push_str(&forbidden);
            out.push_str("\n\n");
        }
    }

    // Fallback sections
    if used_fallback {
        if let Some(readme) = readme_excerpt {
            out.push_str("## README (excerpt)\n```\n");
            out.push_str(readme);
            out.push_str("\n```\n\n");
        }
        if !lang_hist.is_empty() {
            out.push_str("## Language Histogram (top 5 by file count)\n");
            for (ext, count) in lang_hist {
                out.push_str(&format!("- `.{}`: {}\n", ext, count));
            }
            out.push('\n');
        }
        if !tree_entries.is_empty() {
            out.push_str("## File Tree (depth 2)\n```\n");
            for e in tree_entries.iter().take(100) {
                out.push_str(e);
                out.push('\n');
            }
            out.push_str("```\n");
        }
    }

    out
}

// ── Core scan ───────────────────────────────────────────────────

fn do_scan(project_name: &str, project_path: &str, auto_fill: bool) -> Result<ProjectMetadata, String> {
    let root = PathBuf::from(project_path);
    if !root.is_dir() {
        return Err(format!("path is not a directory: {}", project_path));
    }

    let scanned_at = iso_now();

    // 1) Rule docs
    let claude_md = doc_entry_for(&root, "CLAUDE.md");
    let agents_md = doc_entry_for(&root, "AGENTS.md");
    let ai_docs = collect_ai_docs(&root);

    // 2) Parse CLAUDE.md if partial+
    let claude_content = if claude_md.grade == DocGrade::Rich || claude_md.grade == DocGrade::Partial {
        read_to_string_safe(&root.join("CLAUDE.md"))
    } else {
        None
    };
    let sot_doc_raw = claude_content.as_ref().and_then(|c| extract_sot_path(c));

    // 3) Tech stack
    let tech_stack = detect_tech_stack(&root);
    let modules = detect_modules(&root);

    // 4) Quality + SOT resolution
    let quality = overall_quality(&claude_md, &agents_md, &ai_docs);
    let used_fallback = matches!(quality, ProjectQuality::Sparse);

    let (sot_doc, sot_status) = if let Some(p) = sot_doc_raw.clone() {
        let entry = doc_entry_for(&root, &p);
        match entry.grade {
            DocGrade::Rich | DocGrade::Partial => (Some(p), SotStatus::Resolved),
            _ => (Some(p), SotStatus::ReferencedButEmpty),
        }
    } else {
        (None, SotStatus::None)
    };

    // 5) Fallback data
    let (tree_entries, total_files) = if used_fallback {
        let (entries, count) = collect_file_tree(&root, 2);
        (entries, Some(count))
    } else {
        (Vec::new(), None)
    };
    let lang_hist = if used_fallback {
        collect_language_histogram(&root)
    } else {
        Vec::new()
    };
    let readme_excerpt = read_to_string_safe(&root.join("README.md")).map(|c| {
        c.lines()
            .take(50)
            .collect::<Vec<_>>()
            .join("\n")
    });

    // 6) Auto-fill (before composing context, so new files are reflected)
    let mut auto_generated_files: Vec<String> = Vec::new();
    if auto_fill {
        let claude_path = root.join("CLAUDE.md");
        if matches!(claude_md.grade, DocGrade::Missing | DocGrade::Empty) {
            let content = scaffold_claude_md(project_name, &scanned_at, &tech_stack, &modules);
            if safe_write(&claude_path, &content).unwrap_or(false) {
                auto_generated_files.push("CLAUDE.md".to_string());
            }
        }

        // SOT 참조가 있으나 empty/missing인 경우 초안 생성
        if matches!(sot_status, SotStatus::ReferencedButEmpty) {
            if let Some(ref rel) = sot_doc {
                let sot_path = root.join(rel);
                let content = scaffold_architecture_md(project_name, &scanned_at, &tech_stack, &modules);
                if safe_write(&sot_path, &content).unwrap_or(false) {
                    auto_generated_files.push(rel.clone());
                }
            }
        }
    }

    // 7) Re-grade after auto-fill (files may have been created)
    let claude_md_final = doc_entry_for(&root, "CLAUDE.md");
    let agents_md_final = doc_entry_for(&root, "AGENTS.md");
    let ai_docs_final = collect_ai_docs(&root);
    let claude_content_final = if claude_md_final.grade != DocGrade::Missing {
        read_to_string_safe(&root.join("CLAUDE.md"))
    } else {
        None
    };
    let quality_final = overall_quality(&claude_md_final, &agents_md_final, &ai_docs_final);
    let used_fallback_final = matches!(quality_final, ProjectQuality::Sparse);

    // 8) Compose context file
    let context = compose_context_md(
        project_name,
        &scanned_at,
        &tech_stack,
        &claude_md_final,
        &agents_md_final,
        &ai_docs_final,
        &sot_doc,
        sot_status,
        quality_final,
        used_fallback_final,
        &claude_content_final,
        &tree_entries,
        &lang_hist,
        &readme_excerpt,
    );

    let context_path = root.join(CONTEXT_FILE_REL);
    if let Some(parent) = context_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("create .cortx/: {}", e))?;
    }
    fs::write(&context_path, &context).map_err(|e| format!("write context file: {}", e))?;

    Ok(ProjectMetadata {
        scanned_at,
        scanner_version: SCANNER_VERSION,
        tech_stack,
        claude_md: claude_md_final,
        agents_md: agents_md_final,
        ai_docs: ai_docs_final,
        sot_doc,
        sot_status,
        context_file_path: CONTEXT_FILE_REL.to_string(),
        used_fallback: used_fallback_final,
        file_count: total_files,
        overall_quality: quality_final,
        auto_generated_files,
        auto_fill_enabled: auto_fill,
    })
}

// ── Tauri command ──────────────────────────────────────────────

/// 프로젝트 루트를 스캔해 규칙 문서를 인덱싱하고, 부족한 부분을 템플릿으로 보강한다.
/// fire-and-forget — 실제 작업은 백그라운드 스레드에서 수행하고
/// `project-scan-done-{projectId}` 또는 `project-scan-error-{projectId}`로 결과를 emit한다.
#[tauri::command]
pub async fn scan_project(
    app: AppHandle,
    project_id: String,
    project_name: String,
    project_path: String,
    auto_fill: Option<bool>,
) -> Result<(), String> {
    let fill = auto_fill.unwrap_or(true);
    std::thread::spawn(move || {
        log::info!("[scan] start project={} path={} auto_fill={}", project_id, project_path, fill);
        match do_scan(&project_name, &project_path, fill) {
            Ok(metadata) => {
                let event = format!("project-scan-done-{}", project_id);
                if let Err(e) = app.emit(&event, &metadata) {
                    log::warn!("[scan] emit done failed: {}", e);
                }
            }
            Err(err) => {
                log::warn!("[scan] failed for {}: {}", project_id, err);
                let event = format!("project-scan-error-{}", project_id);
                let _ = app.emit(&event, err);
            }
        }
    });
    Ok(())
}

/// 자동 생성된 파일(AUTO-GENERATED 마커 포함)만 삭제한다. 사용자가 편집한 파일은 건너뜀.
#[tauri::command]
pub async fn remove_auto_generated(project_path: String, files: Vec<String>) -> Result<Vec<String>, String> {
    let root = PathBuf::from(&project_path);
    let mut removed: Vec<String> = Vec::new();
    for rel in files {
        let p = root.join(&rel);
        if !p.exists() {
            continue;
        }
        let Ok(content) = fs::read_to_string(&p) else { continue };
        if !content.contains(AUTO_GEN_MARKER) {
            log::info!("[scan] skip remove (marker gone): {}", rel);
            continue;
        }
        if fs::remove_file(&p).is_ok() {
            removed.push(rel);
        }
    }
    Ok(removed)
}
