//! Project scan — 프로젝트 추가 시 백그라운드에서 규칙 문서를 인덱싱하고,
//! 비어있거나 누락된 규칙 문서를 안전 규칙 하에 보강한다.
//!
//! 핵심 원칙:
//! - rich/partial 등급 문서는 절대 건드리지 않음 (AUTO-GENERATED 마커가 없으면)
//! - 출력: `{path}/.cortx/project-context.md` + 기록한 `ProjectMetadata` 이벤트
//!
//! pty.rs/shell.rs와 동일하게 `thread::spawn` + `AppHandle::emit()` 패턴 사용.
//!
//! 서브모듈:
//! - `grader` / `fallback` / `scaffold` / `tech_stack` / `time_utils` — 데이터 수집
//! - `context_md` — `project-context.md` 합성
//! - `orchestrator` — `do_scan` 전체 파이프라인

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;
use tauri::{AppHandle, Emitter};
use ts_rs::TS;

mod context_md;
mod fallback;
mod grader;
mod orchestrator;
mod scaffold;
mod tech_stack;
mod time_utils;

use grader::DocEntry;
use orchestrator::do_scan;

const SCANNER_VERSION: u32 = 1;
const AUTO_GEN_MARKER: &str = "<!-- AUTO-GENERATED by cortx";
const CONTEXT_FILE_REL: &str = ".cortx/project-context.md";
const SCAN_IGNORE_DIRS: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "vendor",
    ".cortx",
    ".venv",
    "__pycache__",
];
const MAX_TREE_FILES: usize = 500;

// ── Types (TS `ProjectMetadata`와 대칭) ─────────────────────────
// DocGrade / DocEntry는 grader 모듈에서 re-use

#[derive(Serialize, Deserialize, Clone, Copy, TS)]
#[serde(rename_all = "snake_case")]
#[ts(export, export_to = "../../src/types/generated/")]
enum SotStatus {
    Resolved,
    ReferencedButEmpty,
    None,
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, TS)]
#[serde(rename_all = "lowercase")]
#[ts(export, export_to = "../../src/types/generated/")]
pub(crate) enum ProjectQuality {
    Rich,
    Partial,
    Sparse,
}

#[derive(Serialize, Deserialize, Clone, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../src/types/generated/")]
pub struct ProjectMetadata {
    scanned_at: String,
    scanner_version: u32,
    tech_stack: Vec<String>,
    claude_md: DocEntry,
    agents_md: DocEntry,
    ai_docs: Vec<DocEntry>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    sot_doc: Option<String>,
    sot_status: SotStatus,
    context_file_path: String,
    used_fallback: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "number")]
    file_count: Option<u64>,
    overall_quality: ProjectQuality,
    auto_generated_files: Vec<String>,
    auto_fill_enabled: bool,
}

// ── Tauri command ──────────────────────────────────────────────

/// 프로젝트 루트를 스캔해 규칙 문서를 인덱싱하고, 부족한 부분을 템플릿으로 보강한다.
/// fire-and-forget — 실제 작업은 백그라운드 스레드에서 수행하고
/// `project-scan-done-{projectId}` 또는 `project-scan-error-{projectId}`로 결과를 emit한다.
#[tauri::command]
pub async fn scan_project(
    app: AppHandle,
    project_id: String,
    project_name: String,
    project_path: String,
    auto_fill: Option<bool>,
) -> Result<(), String> {
    let fill = auto_fill.unwrap_or(true);
    std::thread::spawn(move || {
        log::info!("[scan] start project={} path={} auto_fill={}", project_id, project_path, fill);
        match do_scan(&project_name, &project_path, fill) {
            Ok(metadata) => {
                let event = format!("project-scan-done-{}", project_id);
                if let Err(e) = app.emit(&event, &metadata) {
                    log::warn!("[scan] emit done failed: {}", e);
                }
            }
            Err(err) => {
                log::warn!("[scan] failed for {}: {}", project_id, err);
                let event = format!("project-scan-error-{}", project_id);
                let _ = app.emit(&event, err);
            }
        }
    });
    Ok(())
}

/// 자동 생성된 파일(AUTO-GENERATED 마커 포함)만 삭제한다. 사용자가 편집한 파일은 건너뜀.
#[tauri::command]
pub async fn remove_auto_generated(project_path: String, files: Vec<String>) -> Result<Vec<String>, String> {
    let root = PathBuf::from(&project_path);
    let mut removed: Vec<String> = Vec::new();
    for rel in files {
        let p = root.join(&rel);
        if !p.exists() {
            continue;
        }
        let Ok(content) = fs::read_to_string(&p) else { continue };
        if !content.contains(AUTO_GEN_MARKER) {
            log::info!("[scan] skip remove (marker gone): {}", rel);
            continue;
        }
        if fs::remove_file(&p).is_ok() {
            removed.push(rel);
        }
    }
    Ok(removed)
}
