/**
 * Project scan hook — 전역 이벤트 listener + 트리거 유틸.
 *
 * Rust의 `scan_project` 명령이 백그라운드에서 실행을 마치면
 * `project-scan-done-{projectId}` 이벤트로 ProjectMetadata를 emit하고,
 * 실패 시 `project-scan-error-{projectId}`로 에러 문자열을 emit한다.
 *
 * 이벤트 리스너 등록은 `triggerProjectScan` 내부에서 invoke 전에 끝내므로
 * 스캔 완료 이벤트를 놓치는 경주 조건이 없다.
 */
import { useEffect } from 'react';
import { useProjectStore } from '../stores/projectStore';
import { useScanStatusStore } from '../stores/scanStatusStore';
import type { ProjectMetadata } from '../types/project';

/** 앱 마운트 시 1회 실행 — metadata 없는 프로젝트를 자동 재스캔 (크래시 복구). */
export function useProjectScan(): void {
  useEffect(() => {
    // projects가 아직 로드되기 전일 수 있으므로 subscribe로 반응
    const trigger = (projects: ReturnType<typeof useProjectStore.getState>['projects']) => {
      const scanning = useScanStatusStore.getState().scanning;
      projects.forEach((p) => {
        if (!p.metadata && p.localPath && !scanning.has(p.id)) {
          void triggerProjectScan({
            projectId: p.id,
            projectName: p.name,
            projectPath: p.localPath,
          });
        }
      });
    };

    // 현재 상태 즉시 검사
    trigger(useProjectStore.getState().projects);

    // 이후 projects가 로드될 때도 대응
    const unsub = useProjectStore.subscribe((state) => trigger(state.projects));
    return () => unsub();
  }, []);
}

/** 프로젝트 스캔을 트리거한다. 이벤트 리스너는 invoke 전에 등록되어 완료 이벤트를 놓치지 않는다. */
export async function triggerProjectScan(params: {
  projectId: string;
  projectName: string;
  projectPath: string;
  autoFill?: boolean;
}): Promise<void> {
  useScanStatusStore.getState().start(params.projectId);

  let offDone: (() => void) | null = null;
  let offErr: (() => void) | null = null;
  const cleanup = () => {
    if (offDone) offDone();
    if (offErr) offErr();
    offDone = null;
    offErr = null;
  };

  try {
    const [{ listen }, { invoke }] = await Promise.all([
      import('@tauri-apps/api/event'),
      import('@tauri-apps/api/core'),
    ]);

    // 1) 리스너를 **동시**에 등록 — 직렬 await 사이 경주 창을 없앰
    [offDone, offErr] = await Promise.all([
      listen<ProjectMetadata>(`project-scan-done-${params.projectId}`, (ev) => {
        useProjectStore.getState().updateProject(params.projectId, { metadata: ev.payload });
        useScanStatusStore.getState().finish(params.projectId);
        cleanup();
      }),
      listen<string>(`project-scan-error-${params.projectId}`, (ev) => {
        console.warn(`[scan] ${params.projectId} failed:`, ev.payload);
        useScanStatusStore.getState().finish(params.projectId);
        cleanup();
      }),
    ]);

    // 2) 그 다음 invoke
    await invoke('scan_project', {
      projectId: params.projectId,
      projectName: params.projectName,
      projectPath: params.projectPath,
      autoFill: params.autoFill ?? true,
    });

    // 안전장치: 30초 내 이벤트 미수신 시 자동 해제
    setTimeout(() => {
      if (useScanStatusStore.getState().scanning.has(params.projectId)) {
        console.warn('[scan] timeout — clearing spinner for', params.projectId);
        useScanStatusStore.getState().finish(params.projectId);
        cleanup();
      }
    }, 30000);
  } catch (err) {
    const msg = String(err);
    console.error('[scan] invoke failed:', err);
    if (msg.includes('not found') || msg.includes('unknown command')) {
      console.error(
        '%c[scan] Rust command `scan_project`가 등록되지 않았습니다. `pnpm tauri dev`를 완전히 종료 후 재시작하세요.',
        'color: #f87171; font-weight: bold; font-size: 14px;',
      );
    }
    useScanStatusStore.getState().finish(params.projectId);
    cleanup();
  }
}

/** 자동 생성된 스캐폴드 파일들을 되돌린다. */
export async function removeAutoGenerated(projectPath: string, files: string[]): Promise<string[]> {
  try {
    const { invoke } = await import('@tauri-apps/api/core');
    return await invoke<string[]>('remove_auto_generated', { projectPath, files });
  } catch (err) {
    console.error('[removeAutoGenerated] invoke failed:', err);
    return [];
  }
}
