/**
 * @module types/project
 * 프로젝트 도메인 타입 정의.
 * 프로젝트는 GitHub 저장소와 1:1로 매핑되며, 여러 Task를 그룹핑한다.
 */

/** 문서 유효성 등급 — 파일 존재만으로는 "내용 있음"을 판단하지 않음 */
export type DocGrade = 'rich' | 'partial' | 'empty' | 'missing';

/** 단일 규칙 문서의 상태 스냅샷 */
export interface DocEntry {
  /** 프로젝트 루트 기준 상대 경로 */
  path: string;
  grade: DocGrade;
  sizeBytes: number;
  firstH1?: string;
}

/** SOT(Single Source of Truth) 문서 해결 상태 */
export type SotStatus = 'resolved' | 'referenced_but_empty' | 'none';

/** 전체 품질 등급 — UI 뱃지 색상 결정에 사용 */
export type ProjectQuality = 'rich' | 'partial' | 'sparse';

/** 스캔 결과 요약. dev-task가 `.cortx/project-context.md`를 읽어 활용하고,
 *  이 구조체는 UI 뱃지·재스캔 힌트·롤백 버튼에 사용된다. */
export interface ProjectMetadata {
  /** ISO 8601 타임스탬프 */
  scannedAt: string;
  /** 스캐너 포맷 버전 — 호환되지 않는 변경 시 bump */
  scannerVersion: number;
  /** 매니페스트 기반 감지 스택 (예: "Java 17", "Spring Boot 2.7") */
  techStack: string[];
  claudeMd: DocEntry;
  agentsMd: DocEntry;
  /** `.ai/docs/` 안의 모든 `.md` 파일 */
  aiDocs: DocEntry[];
  /** CLAUDE.md가 참조한 SOT 문서의 프로젝트 루트 기준 경로 */
  sotDoc?: string;
  sotStatus: SotStatus;
  /** 생성된 컨텍스트 파일 경로 (프로젝트 루트 기준) */
  contextFilePath: string;
  /** 최고 등급 문서가 partial 미만이어서 fallback 섹션을 포함한 경우 true */
  usedFallback: boolean;
  /** fallback 시 수집한 파일 개수 */
  fileCount?: number;
  overallQuality: ProjectQuality;
  /** AUTO-GENERATED 마커가 포함된 파일 경로 (롤백 대상) */
  autoGeneratedFiles: string[];
  /** 자동 보강 활성화 여부 — 기본 true */
  autoFillEnabled: boolean;
}

/** 프로젝트 — GitHub 저장소 기반의 작업 그룹 */
export interface Project {
  id: string;
  /** 프로젝트 표시 이름 */
  name: string;
  /** 로컬 git 저장소 경로 */
  localPath: string;
  /** GitHub 소유자 (user 또는 org) */
  githubOwner: string;
  /** GitHub 저장소 이름 */
  githubRepo: string;
  /** PR 생성 시 기본 대상 브랜치 */
  baseBranch: string;
  /** 모니터링할 Slack 채널 ID 목록 */
  slackChannels: string[];
  /** UI에서 사용하는 프로젝트 구분 색상 (hex) */
  color: string;
  createdAt: string;
  /** 프로젝트 추가 시 백그라운드 스캔 결과. 스캔 완료 전에는 undefined. */
  metadata?: ProjectMetadata;
}
